import { useEffect, useState } from 'react';
import { loadIconLibrary, loadIconCatalog, type IconCatalog } from '@/data/icons';
import type { IconLibrary, Module, Variable } from '@/data/preset-contract/types';
export default function IconographyDemo({module,edits,onEdit}:{module:Extract<Module,{module:'iconography'}>;edits:Record<string,string>;onEdit:(edits:Record<string,string>)=>void}){
  const [catalog,setCatalog]=useState<IconCatalog>(),[library,setLibrary]=useState<IconLibrary>(),[query,setQuery]=useState(''),[name,setName]=useState(''),[variant,setVariant]=useState(''),[error,setError]=useState('');
  const vars=module.submodules.flatMap(s=>s.variables),config=module.configuration;
  const token=(id:string)=>vars.find(v=>v.id===id)!;
  const value=(id:string)=>edits[id]??token(id).displayValue;
  const selected=value(config.library);
  useEffect(()=>{loadIconCatalog().then(setCatalog).catch(e=>setError(String(e)));},[]);
  useEffect(()=>{let active=true;setLibrary(undefined);loadIconLibrary(selected).then(l=>{if(active){setLibrary(l);setVariant(l.variants[0]);setQuery('');setName('');}}).catch(e=>active&&setError(String(e)));return()=>{active=false;};},[selected]);
  if(!library||!catalog)return <p role="status">{error||'Loading official icons…'}</p>;
  const icons=library.icons.filter(i=>i.variant===variant),icon=icons.find(i=>i.name===name)||icons.find(i=>['home','house','house-door'].includes(i.name))||icons[0];
  const size=Math.max(1,parseFloat(value(config.baseSize)));
  const preview=(svg:string,size:number)=> <span role="img" aria-label={icon.name} className="demo-icon-svg" style={{width:size,height:size}} dangerouslySetInnerHTML={{__html:svg}}/>;
  const select=(label:string,id:string,values:string[])=> <label>{label}<select aria-label={label} value={value(id)} onChange={e=>onEdit({[id]:e.target.value})}>{values.map(v=><option key={v}>{v}</option>)}</select></label>;
  return <><details open><summary>Library</summary><div className="demo-fields"><label>Icon Library<select aria-label="Icon Library" value={selected} onChange={e=>onEdit({[config.library]:e.target.value})}>{catalog.libraries.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>{select('Delivery',config.delivery,library.delivery)}</div></details><details open><summary>Sizing</summary><div className="demo-fields"><label>Native Size<output>{library.nativeSize}</output></label><label>Base Size (px)<input aria-label="Icon Base Size" type="number" min="1" value={size} onChange={e=>e.target.valueAsNumber>0&&onEdit({[config.baseSize]:`${e.target.value}px`})}/></label><label>Project Size Scale<output>{config.scale.steps.map(id=>parseFloat(value(id))).join(' / ')}</output></label><small>{config.description}</small><button className="demo-generate-scale" onClick={()=>onEdit(Object.fromEntries(vars.filter(v=>config.scale.steps.includes(v.id)).map(v=>[v.id,`${Number((Number(v.value)*size/config.scale.baseValue).toFixed(4))}px`])))}>Generate icon scale</button></div></details><details open><summary>Behavior</summary><div className="demo-fields">{select('Color Behavior',config.colorBehavior,['currentColor','inherit'])}<label>Variant<select aria-label="Icon Variant" value={variant} onChange={e=>setVariant(e.target.value)}>{library.variants.map(v=><option key={v}>{v}</option>)}</select></label>{config.verticalAlign&&<label>Vertical Align<input value={value(config.verticalAlign)} onChange={e=>onEdit({[config.verticalAlign!]:e.target.value})}/></label>}</div></details><details open><summary>Preview</summary><input aria-label="Search icons" placeholder="Search icons by name or tag…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="demo-icon-grid">{icons.filter(i=>`${i.name} ${i.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())).slice(0,100).map(i=><button key={i.name} aria-label={`Preview ${i.name}`} onClick={()=>setName(i.name)} title={i.name}>{preview(i.svg,24)}<small>{i.name}</small></button>)}</div></details><details open><summary>Generated scale</summary>{config.scale.steps.map(id=><div key={id} className="demo-type-preview">{preview(icon.svg,parseFloat(value(id)))}<span>{library.name}</span><span><small>{value(id)}</small><code>{token(id).name}</code></span></div>)}</details></>;
}
