function MI({
  icon,
  size = 20,
  fill = 0,
  className = "",
  style = {},
}: {
  icon: string;
  size?: number;
  fill?: 0 | 1;
  className?: string;
  style?: React.CSSProperties;
}) {
  return (
    <span
      className={`material-symbols-outlined select-none leading-none ${className}`}
      style={{
        fontSize: size,
        fontVariationSettings: `'FILL' ${fill}, 'wght' 400, 'GRAD' 0, 'opsz' ${size}`,
        lineHeight: 1,
        display: "inline-flex",
        alignItems: "center",
        ...style,
      }}
    >
      {icon}
    </span>
  );
}

export default function Terms() {
  return (
    <div
      className="min-h-screen bg-background text-foreground"
      style={{ fontFamily: "'Source Sans 3', system-ui, sans-serif" }}
    >
      <section className="py-24">
        <div className="max-w-6xl mx-auto px-6">
          <div className="max-w-3xl">
            <h1 className="text-4xl font-bold text-foreground tracking-[-0.02em] mb-6">
              Terms of Service
            </h1>
            <p className="text-base text-muted-foreground mb-12 leading-relaxed">
              Last updated: January 2025
            </p>

            <div className="space-y-8">
              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  Acceptance of Terms
                </h2>
                <p className="text-base text-muted-foreground leading-relaxed">
                  By accessing or using DS Boilerplate, you agree to be bound by these Terms of Service. 
                  If you do not agree to these terms, please do not use our service.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  Description of Service
                </h2>
                <p className="text-base text-muted-foreground leading-relaxed">
                  DS Boilerplate is a Figma plugin that generates design systems and variables. 
                  We offer both free and paid subscription plans with different features and limitations.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  Subscription Plans
                </h2>
                <p className="text-base text-muted-foreground leading-relaxed">
                  We offer monthly and lifetime subscription plans. Monthly subscriptions can be cancelled 
                  at any time. Lifetime access provides unlimited use of the service. All subscriptions 
                  include future updates to the plugin.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  Payment Terms
                </h2>
                <p className="text-base text-muted-foreground leading-relaxed">
                  Payments are processed through Stripe. By subscribing, you authorize us to charge 
                  your payment method for the selected plan. Refunds may be provided at our discretion 
                  in accordance with applicable laws.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  User Responsibilities
                </h2>
                <p className="text-base text-muted-foreground leading-relaxed">
                  You agree to use DS Boilerplate only for lawful purposes and in accordance with these 
                  Terms. You may not use the service to generate content that violates intellectual 
                  property rights or is otherwise illegal.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  Intellectual Property
                </h2>
                <p className="text-base text-muted-foreground leading-relaxed">
                  DS Boilerplate and its original content, features, and functionality are owned by us 
                  and are protected by international copyright, trademark, and other intellectual property 
                  laws. Design systems generated by users remain their property.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  Limitation of Liability
                </h2>
                <p className="text-base text-muted-foreground leading-relaxed">
                  To the fullest extent permitted by law, we shall not be liable for any indirect, 
                  incidental, special, or consequential damages arising from your use of DS Boilerplate.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  Changes to Terms
                </h2>
                <p className="text-base text-muted-foreground leading-relaxed">
                  We reserve the right to modify these terms at any time. We will notify users of 
                  significant changes via email or through the plugin.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  Contact Us
                </h2>
                <p className="text-base text-muted-foreground leading-relaxed">
                  If you have any questions about these Terms of Service, please contact us through 
                  our contact page.
                </p>
              </section>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
