import {test} from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import vm from 'node:vm';
const bundle=await build({entryPoints:['src/utils/analytics.ts'],bundle:true,write:false,format:'cjs'});
function setup(){const calls={ga:[],clarity:[],hj:[],scripts:[]},storage=new Map();const location=new URL('https://starttokens.test/?email=private%40test.com&utm_source=qa&utm_medium=test&utm_campaign=analytics&analytics_debug=1');const state={key:'router',idx:4};const window={location,dataLayer:[],gtag:(...a)=>calls.ga.push(a),clarity:(...a)=>calls.clarity.push(a),hj:(...a)=>calls.hj.push(a),history:{state,replaceState(s,t,url){assert.equal(s,state);location.href=new URL(url,location).href;}}};const module={exports:{}};vm.runInNewContext(bundle.outputFiles[0].text,{module,exports:module.exports,window,document:{title:'StartTokens',head:{appendChild:n=>calls.scripts.push(n)},getElementById:()=>null,createElement:()=>({})},sessionStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},URLSearchParams,console});return {api:module.exports,window,calls};}
test('one manual page_view per route transition; hashes do not produce pageviews',()=>{const {api,window,calls}=setup();api.initializeAnalytics();api.initializeAnalytics();assert.equal(calls.scripts.length,3);assert.equal(calls.ga.find(x=>x[0]==='config')[2].send_page_view,false);api.trackPageView('/');api.trackPageView('/');api.trackSectionView('hero','none');api.trackSectionView('hero','none');api.trackSectionView('pricing','down');api.trackSectionView('faq','down');api.trackSectionView('pricing','up');assert.equal(calls.ga.filter(x=>x[1]==='page_view').length,1);assert.equal(calls.ga.filter(x=>x[1]==='pricing_view').length,1);assert.equal(calls.ga.filter(x=>x[1]==='section_view').at(-1)[2].previous_section,'faq');assert.equal(window.location.hash,'#pricing');for(const path of ['/privacy','/terms','/contact','/success','/cancel','/']){window.location.pathname=path;api.trackPageView(path);api.trackPageView(path);}assert.equal(calls.ga.filter(x=>x[1]==='page_view').length,7);assert.equal(calls.ga.filter(x=>x[1]==='checkout_success_view').length,1);assert.equal(calls.ga.filter(x=>x[1]==='checkout_cancelled').length,1);assert.ok(!calls.ga.some(x=>x[1]==='purchase'));});
test('common context reaches all adapters without email, query URL or user ID',()=>{const {api,calls}=setup();api.initializeAnalytics();api.trackPageView('/');api.trackSectionView('pricing','down');api.trackPricingClick('annual','new');api.trackCheckoutStarted('annual','new');api.trackFigmaInstallClick();api.trackFAQExpand('Question');for(const name of ['page_view','section_view','pricing_view','pricing_click','checkout_started','figma_install_click','faq_expand']){assert.ok(calls.ga.some(x=>x[1]===name));assert.ok(calls.clarity.some(x=>x[0]==='event'&&x[1]===name));assert.ok(calls.hj.some(x=>x[0]==='event'&&x[1]===name));}const data=calls.ga.find(x=>x[1]==='checkout_started')[2];assert.equal(data.source,'qa');assert.equal(data.plan,'annual');assert.equal(data.pricing_version,'new');assert.doesNotMatch(JSON.stringify(calls),/private|email=|install_plugin_click/);assert.ok(calls.hj.some(x=>x[0]==='identify'&&x[1]===null&&x[2].section_id==='pricing'));});
test('provider errors do not interrupt other adapters or checkout',()=>{const {api,window,calls}=setup();window.gtag=()=>{throw Error('blocked');};api.initializeAnalytics();api.trackCheckoutStarted('monthly','new');assert.ok(calls.hj.some(x=>x[1]==='checkout_started'));});
test('purchase is a validated server-only Measurement Protocol payload',()=>{const {api,calls}=setup();const payload=api.buildPurchaseMeasurementPayload({client_id:'123.456',transaction_id:'cs_verified',value:59.99,currency:'USD',plan:'annual',pricing_version:'new'});assert.equal(payload.events[0].name,'purchase');assert.equal(payload.events[0].params.transaction_id,'cs_verified');assert.equal(calls.ga.length,0);assert.throws(()=>api.buildPurchaseMeasurementPayload({client_id:'x',transaction_id:'',value:NaN,currency:'USD',plan:'annual',pricing_version:'new'}));});
