import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
const output='validation-output/foundations';mkdirSync(output,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:420,height:747}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{
  window.__pluginRequests=[];
  window.addEventListener('message',e=>{
    const m=e.data?.pluginMessage;if(!m)return;
    window.__pluginRequests.push(m);
    if(m.type==='list-fonts')window.postMessage({pluginMessage:{type:'available-fonts',fonts:[{family:'Inter',style:'Regular'},{family:'Team Custom Font',style:'Regular'},{family:'Roboto',style:'Regular'}]}},'*');
    if(m.type==='validate-font')window.postMessage({pluginMessage:{type:'font-validation-result',requestId:m.requestId,ok:m.font.family!=='Team Custom Font',error:'Font load failed'}},'*');
  });
});
await page.route(/fonts.googleapis.com|fonts.gstatic.com/,r=>r.abort());
await page.goto('http://127.0.0.1:5175',{waitUntil:'domcontentloaded'});
await page.getByRole('button',{name:'Bootstrap',exact:true}).click();
assert.deepEqual(await page.getByRole('tab').allTextContents(),['paletteColors','font_downloadTypography','wallpaperIcons','grid_4x4Layout']);
await page.getByRole('tab',{name:/Typography/}).click();
assert.equal(await page.getByRole('button',{name:'Secondary Font',exact:true}).count(),0);
await page.getByRole('button',{name:'Primary Font',exact:true}).click();
await page.getByRole('textbox',{name:'Search Primary Font'}).fill('Team');
await page.getByRole('button',{name:/Team Custom Font/}).click();
await page.getByRole('alert').filter({hasText:'Font load failed'}).waitFor();
await page.getByRole('textbox',{name:'Search Primary Font'}).fill('Inter');
await page.getByRole('button',{name:/Inter.*quick brown/}).click();
await page.getByRole('button',{name:'Primary Font',exact:true}).filter({hasText:'Inter'}).waitFor();
await page.locator('[data-slot=popover-content]').waitFor({state:'hidden'});
await page.setViewportSize({width:420,height:1900});
await page.screenshot({path:output+'/plugin-typography.png',animations:'disabled'});
await page.getByRole('tab',{name:/Icons/}).click();
await page.getByRole('combobox',{name:'Icon Library'}).selectOption('lucide');
await page.getByText('Browse icons',{exact:true}).click();
await page.getByRole('textbox',{name:'Search icons'}).fill('heart');
await page.getByRole('button',{name:'Preview heart',exact:true}).click();
await page.getByRole('textbox',{name:'Base Size (px)',exact:true}).fill('32');
await page.getByRole('button',{name:'Generate icon scale'}).click();
await page.getByRole('combobox',{name:'Insert icon size'}).selectOption({label:'icon-size-md · 40px'});
await page.getByRole('button',{name:'Insert icon',exact:true}).click();
await page.waitForFunction(()=>window.__pluginRequests.some(m=>m.type==='insert-icon'));
const request=await page.evaluate(()=>window.__pluginRequests.findLast(m=>m.type==='insert-icon'));
assert.equal(request.size,40);assert.match(request.svg,/<svg/);assert.match(request.name,/Lucide \/ heart/);
await page.getByRole('combobox',{name:'Icon Library'}).selectOption('bootstrap-icons');
await page.getByRole('textbox',{name:'Base Size (px)',exact:true}).fill('16');
await page.getByRole('button',{name:'Generate icon scale'}).click();
await page.getByText('Browse icons',{exact:true}).click();
await page.locator('main').evaluate(el=>el.scrollTop=0);
await page.screenshot({path:output+'/plugin-icons.png',animations:'disabled'});
await page.getByRole('button',{name:'Generate tokens',exact:true}).click();
await page.waitForFunction(()=>window.__pluginRequests.some(m=>m.type==='generate-variables'));
const generated=await page.evaluate(()=>window.__pluginRequests.findLast(m=>m.type==='generate-variables'));
assert.equal(generated.modules.length,4);assert.ok(generated.iconPreview.svg.includes('<svg'));assert.ok(!generated.tokens.some(t=>String(t.value).includes('<svg')));
await page.getByRole('button',{name:'Back to presets',exact:true}).click();
await page.getByRole('button',{name:'Material Design',exact:true}).click();
await page.getByRole('button',{name:'Switch preset',exact:true}).click();
await page.getByRole('tab',{name:/Typography/}).click();
await page.getByRole('button',{name:'Secondary Font',exact:true}).click();
await page.getByRole('textbox',{name:'Search Secondary Font'}).fill('Inter');
await page.getByRole('button',{name:/Inter.*quick brown/}).click();
await page.getByRole('button',{name:'Secondary Font',exact:true}).filter({hasText:'Inter'}).waitFor();
const body=page.locator('span[title="--md-sys-typescale-body-large-size"]');
assert.match(await body.evaluate(el=>el.style.fontFamily),/Inter/);assert.equal(await body.evaluate(el=>el.style.fontWeight),'400');
assert.match(await page.getByRole('button',{name:'Primary Font',exact:true}).innerText(),/Roboto/);
await page.setViewportSize({width:1440,height:1000});
await page.goto('http://127.0.0.1:5174',{waitUntil:'domcontentloaded'});
const demo=page.locator('#hero .plugin-demo');await demo.getByRole('button',{name:'Tailwind CSS',exact:true}).click();
await demo.getByRole('tab',{name:/Typography/}).click();await demo.getByLabel('Secondary Font',{exact:true}).fill('Georgia');
await demo.getByRole('tab',{name:/Icons/}).click();await demo.getByLabel('Icon Library',{exact:true}).selectOption('phosphor');
await demo.getByRole('textbox',{name:'Search icons'}).fill('heart');await demo.getByRole('button',{name:'Preview heart',exact:true}).click();
await demo.screenshot({path:output+'/lp-icons.png'});
assert.deepEqual(errors,[]);writeFileSync(output+'/report.json',JSON.stringify({passed:true,checks:['font search, failed load, successful load','native supported semantic controls','library search and preview','preset scale regeneration','insert configured size','configuration Variables without SVGs','LP semantic fonts and icon browser']},null,2));
await browser.close();console.log('Foundations UI: all interaction checks passed; screenshots saved.');
